version: '3'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: web_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: web_radgj@123
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: 'postgres://root:web_radgj@123@db:5432/web_db'
      

